# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  pr_merge:
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: packer build ubuntu-ami.json

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  pr-merge:
    jobs:
      - pr_merge